version: '3.8'

services:
  nginx-frontend:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        # Die URL, über die der Webserver vom Backend erreichbar ist.
        base_url: http://localhost:8080
    environment:
      NODE_ENV: production
    ports:
      - "8082:80"
    networks:
      - "news-articles-backend_default"

networks:
  news-articles-backend_default:
    external: true
