version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    environment:
      NODE_ENV: production
      NODE_OPTIONS: --openssl-legacy-provider # Workaround für ein webpack Bug mit der aktuellen node-Version (https://github.com/webpack/webpack/issues/14532)
      REACT_APP_BACKEND_BASE_URL: news-article-backend_nginx
    ports:
      - "8082:80"
    networks:
      - "news-articles-backend_default"

networks:
  news-articles-backend_default:
    external: true
